### ISSUE TITLE
Issue when I save on the plugin

### ISSUE THREAD

**Issue by Migaloodigital** [and-pay/woocommerce-gateway-andpay#1]
I got this message:

6 /home/nimblo/webapps/mngo/wp-includes/class-wp-hook.php(303): WC_Settings_Pa" while reading response header from upstream, client: 203.206.211.210, server: mngo.xyz, request: "POST /wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce-gateway-andpay HTTP/2.0", upstream: "fastcgi://unix:/var/run/mngo.sock:", host: "mngo.xyz", referrer: "https://mngo.xyz/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce-gateway-andpay"
#5 /home/nimblo/webapps/mngo/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(230): do_action()
#4 /home/nimblo/webapps/mngo/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /home/nimblo/webapps/mngo/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /home/nimblo/webapps/mngo/wp-includes/class-wp-hook.php(303): Andpay_Gateway->process_admin_options()
#1 /home/nimblo/webapps/mngo/wp-content/plugins/woocommerce-gateway-andpay-master/includes/class-andpay-gateway.php(269): Andpay_Gateway->authenticate_api()
#0 /home/nimblo/webapps/mngo/wp-content/plugins/woocommerce-gateway-andpay-master/includes/class-andpay-gateway.php(47): Andpay_Client::authenticate()

**Stack trace:**

2021/11/12 02:51:03 [error] 30370#30370: *12479 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Andpay\Client' not found in /home/nimblo/webapps/mngo/wp-content/plugins/woocommerce-gateway-andpay-master/includes/class-andpay-client.php:31
2021/11/12 02:49:49 [error] 30370#30370: *12479 FastCGI sent in stderr: "PHP message: PHP Warning:  array_column() expects parameter 1 to be array, string given in /home/nimblo/webapps/mngo/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php on line 27PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/nimblo/webapps/mngo/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/Count.php on line 24" while reading response header from upstream, client: 203.206.211.210, server: mngo.xyz, request: "GET /wp-json/wc-admin/onboarding/free-extensions?_locale=user HTTP/2.0", upstream: "fastcgi://unix:/var/run/mngo.sock:", host: "mngo.xyz", referrer: "https://mngo.xyz/wp-admin/admin.php?page=wc-admin"

**Comment by andpay-io** [comment]
Hi @Migaloodigital,

Thanks for trying out Andpay! 

We just noticed that a folder was not correctly pushed towards our Github repository, therefore resulting in that error. Could you retry downloading the latest ZIP from this repository and try again? That should work and not give any errors (tried and tested).
