### ISSUE TITLE
Can't add price above 999

### ISSUE THREAD

**Issue by Migaloodigital** [and-pay/woocommerce-gateway-andpay#3]
Hi team,

I'm facing an issue on our website, ww are using you plugin te let client pay in Algo for donation purpose. If someone try to add a value above 999 the website doesn't show the good value, if I deactivate your plugin the values are good. 

Let us know what we should do, I have contacted the other plugin dev and the plugin works fine without yours...
This is the name of the plugin we use with Algo payment: ELEX WooCommerce Name Your Price

Thank you for your help.

**Comment by andpay-io** [comment]
Hi @Migaloodigital,

Somehow we haven't received a notification from Github of your issue. So pardon us for the late reply. We'll have a look at what's going wrong here and will update you in the coming days.

**Comment by andpay-io** [comment]
Hi @Migaloodigital,

We found the issue and released a new version (1.0.3) containing a fix for the thousands (and upwards). Please update your plugin version to the latest one and the issue should be resolved.

Let us know if you have more feedback! For now we'll close this thread, considered it should be resolved.

**Comment by Migaloodigital** [comment]
Hi @andpay-io and thanks a lot for your reactivity. Everything is working for this part.

We have another issue. Majority of payment get declined on Andpay screen...

**Comment by andpay-io** [comment]
Hi @Migaloodigital ,

What do you mean with declined on the Andpay screen? Do you have a screenshot or message that indicates a decline? Tried to look it up in our error logging, but didn't saw anything yet. 

Next to that - do you still see the transaction succeed on the blockchain itself?
